apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: anp-agent
  name: anp-agent
spec:
  selector:
    matchLabels:
      app: anp-agent
  template:
    metadata:
      labels:
        app: anp-agent
    spec:
      hostAliases:
        - ip: "127.0.0.1"
          hostnames:
            - "{{.CLUSTER_ID}}"
      containers:
        - name: apiserver-proxy
          image: {{.CLUSTER_IMAGE}}
          command:
            - "/apiserver-proxy"
          ports:
            - containerPort: {{.APISERVER_PROXY_PORT}}
        - name: proxy-agent
          image: {{.CLUSTER_IMAGE}}
          command:
            - "/proxy-agent"
            - "--proxy-server-host={{.PROXY_SERVER_ADDRESS}}"
            - "--proxy-server-port={{.PROXY_SERVER_PORT}}"
            - "--agent-identifiers=host={{.CLUSTER_ID}}"
            - "--ca-cert=/certs/cluster-proxy-ca.crt"
            - "--agent-cert=/certs/cluster-proxy-agent.crt"
            - "--agent-key=/certs/cluster-proxy-agent.key"
          livenessProbe:
            httpGet:
              scheme: HTTP
              port: 8093
              path: /healthz
            initialDelaySeconds: 15
            timeoutSeconds: 15
          volumeMounts:
            - name: certs
              mountPath: /certs
              readOnly: true
      volumes:
        - name: /certs
          secret:
            secretName: certs