apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: anp-server
  name: anp-server
spec:
  selector:
    matchLabels:
      app: anp-server
  template:
    metadata:
      labels:
        app: anp-server
    spec:
      containers:
        - name: proxy-server
          image: cluster-proxy-addon
          command:
            - "/proxy-server"
            - "--mode=http-connect"
            - "--agent-port={{ .PROXY_SERVER_PORT }}"
            - "--cluster-ca-cert=/certs/cluster-proxy-ca.crt"
            - "--cluster-cert=/certs/cluster-proxy-server.crt"
            - "--cluster-key=/certs/cluster-proxy-server.key"
            - "--proxy-strategies=destHost"
            - "--uds-name=/cluster-proxy-addon-socket"
            - "--delete-existing-uds-file=true"
          volumeMounts:
            - name: certs
              mountPath: /certs
              readOnly: true
          ports:
            - name: agentport
              containerPort: {{ .PROXY_SERVER_PORT }}
        - name: user-server
          image: cluster-proxy-addon
          command:
            - "/user-server"
            - "--server-port={{ .USER_SERVER_PORT }}"
            - "--server-key=/certs/cluster-proxy-server.key"
            - "--server-cert=/certs/cluster-proxy-server.crt"
            - "--proxy-uds=/cluster-proxy-addon-socket"
          volumeMounts:
            - name: certs
              mountPath: /certs
              readOnly: true
          ports:
            - name: userport
              containerPort: {{ .USER_SERVER_PORT }}
      volumes:
        - name: certs
          secret:
            secretName: certs