apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: submariner-addon
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-proxy-addon
subjects:
- kind: ServiceAccount
  name: cluster-proxy-addon
  namespace: open-cluster-management
