apiVersion: proxy.open-cluster-management.io/v1alpha1
kind: ManagedProxyConfiguration
metadata:
  name: cluster-proxy
spec:
  authentication:
    dump:
      secrets: {}
    signer:
      type: SelfSigned
  proxyServer:
    image: {{ .Values.global.imageOverrides.cluster_proxy_addon }}
    namespace: {{ .Release.Namespace }}
    replicas: {{ .Values.replicas }}
    entrypoint:
      type: Hostname
      hostname:
        value: {{ template "cluster-proxy-addon.anpPublicHost" . }}
      port: 443
    additionalArgs:
      - "--keepalive-time=30s" # Use this to keep connection from proxy-agent stay alive
      - "--cipher-suites=TLS_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256,TLS_RSA_WITH_AES_256_CBC_SHA,TLS_RSA_WITH_AES_128_GCM_SHA256,TLS_AES_128_GCM_SHA256,TLS_CHACHA20_POLY1305_SHA256,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256,TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA"
    nodePlacement:
      tolerations:
          - key: dedicated
            operator: Exists
            effect: NoSchedule
          - effect: NoSchedule
            key: node-role.kubernetes.io/infra
            operator: Exists
      {{- with .Values.hubconfig.nodeSelector }}
      nodeSelector:
  {{ toYaml . | indent 8 }}
      {{- end }}
  proxyAgent:
    image: {{ .Values.global.imageOverrides.cluster_proxy_addon }}
    replicas: {{ .Values.replicas }}
    {{- if .Values.global.imagePullSecret }}
    imagePullSecrets:
    - "{{ .Values.global.imagePullSecret }}"
    {{- end }}
